# -*- coding: utf-8 -*-
"""GBPUSDmodel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jn7A_vDHB8m0BF_lIhyXcrLz11MEII74
"""

import pickle
from flask import Flask, render_template, request

filename = 'GBPUSD_model.pkl'
model = pickle.load(open(filename, 'rb'))

app = Flask(__name__)

@app.route('/<string:data>', methods=['POST', 'GET'])
def predict(data):
  parts = data.split(',')
  d1 = []
  d2 = []
  dataset = []
  
  for i in parts:
    d1.append(float(i))
    d2.append(float(i))
    
  dataset = [d1, d2]
  
  result = model.predict(dataset)
  return str(result)

if __name__ == '__main__':
  app.secret_key = '491071'
  app.run(host='0.0.0.0', port='9999', debug=False)